# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_subject'),
        ('office', '0007_gallaryvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.School')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Section')),
            ],
        ),
    ]
