# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='name_with_int',
        ),
    ]
