# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180211_0022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTestExamTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.School')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Subject')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
