# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_classtestexamtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtestexamtime',
            name='exam_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
