# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0004_classtestexammark'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtestexammark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classtestexammark',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adder', to=settings.AUTH_USER_MODEL),
        ),
    ]
